env:
  # where on disk the Qlib binary data lives
  provider_uri: "~/.qlib/qlib_data/cn_data"

  # which market conventions to use ("cn" or "us")
  region: "cn"

  # which universe file under instruments/ to load
  universe_file: "csiall.txt"

  # backtest period
  start_date: "2015-01-01"
  end_date:   "2024-12-31"

  # which fields to load
  fields:
    - "$open"
    - "$high"
    - "$low"
    - "$close"
    - "$volume"

  # optional: just load N tickers for quick sanity checks
  sample_size: 50

policy:
  # (leave empty or put your PPO‐specific hyperparams here later)

training:
  # (leave empty or put your trainer hyperparams here later)