# configs/config.yaml

env:
  provider_uri: "~/.qlib/qlib_data/cn_data"
  region: "cn"
  universe_file: "csiall.txt"
  start_date: "2015-01-01"
  end_date: "2024-12-31"
  sample_size: 50

policy:
  # hidden layer sizes for actor & critic
  hidden_sizes: [128, 128]
  # learning rate for optimizer
  lr: 3e-4
  # PPO hyperparams
  discount_factor: 0.99
  gae_lambda: 0.95
  eps_clip: 0.2
  value_coef: 0.5
  ent_coef: 0.0
  batch_size: 64
  step_per_epoch: 1000
  repeat_per_collect: 4

training:
  # how many parallel envs to collect from
  n_train_envs: 8
  n_test_envs: 2
  buffer_size: 20000
  max_epoch: 50
  log_dir: "~/runs/rl_order_exec"
