# configs/config.yaml

env:
  # where on disk the QLib binary data lives
  provider_uri: "~/.qlib/qlib_data/cn_data"
  # which market conventions to use (“cn” or “us”)
  region: "cn"
  # single‐asset execution settings:
  instrument: "SZ000001"            # <-- e.g. pick one to train on
  start_time: "2025-05-22 09:31:00" # order’s start time (ISO format)
  end_time:   "2025-05-22 15:00:00" # order’s end time
  amount: 100000                    # total shares to execute
  direction: "buy"                  # "buy" or "sell"

policy:
  # network + PPO hyperparameters
  hidden_sizes: [128, 128]
  lr: 3e-4
  discount_factor: 0.99
  gae_lambda: 0.95
  eps_clip: 0.2
  value_coef: 0.5
  ent_coef: 0.0
  batch_size: 64
  step_per_epoch: 1000
  repeat_per_collect: 4

training:
  # how many parallel envs for data collection & evaluation
  n_train_envs: 8
  n_test_envs: 2
  buffer_size: 20000
  max_epoch: 50
  log_dir: "~/runs/rl_order_exec"
